import { FC } from "react";
import { OrderListItem } from "../../../components/order-list-item/order-list-item";
import styles from "./orders.module.css";
import { OrderStatus } from "../../../models";

export const ProfileOrdersPage: FC = () => {
  return (
    <div className={styles.container}>
      <OrderListItem
        date="2022-03-05T01:23:45"
        id="0123"
        status={OrderStatus.Created}
        ingredients={
          [
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
          ] as any
        }
        price={456}
        title="some"
      />
      <OrderListItem
        date="2022-03-05T01:23:45"
        id="0123"
        status={OrderStatus.Created}
        ingredients={
          [
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
          ] as any
        }
        price={456}
        title="some"
      />
      <OrderListItem
        date="2022-03-05T01:23:45"
        id="0123"
        status={OrderStatus.Created}
        ingredients={
          [
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
          ] as any
        }
        price={456}
        title="some"
      />
      <OrderListItem
        date="2022-03-05T01:23:45"
        id="0123"
        status={OrderStatus.Created}
        ingredients={
          [
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
          ] as any
        }
        price={456}
        title="some"
      />
      <OrderListItem
        date="2022-03-05T01:23:45"
        id="0123"
        status={OrderStatus.Created}
        ingredients={
          [
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
            {
              image_mobile:
                "https://code.s3.yandex.net/react/code/cheese-mobile.png",
            },
          ] as any
        }
        price={456}
        title="some"
      />
    </div>
  );
};
