import { FC } from "react";
import styles from "./feed.module.css";
import { OrderListItem } from "../../components/order-list-item/order-list-item";
import {
  OrderNumbers,
  OrderNumbersMode,
} from "../../components/order-numbers/order-numbers";
import { formattedAmount } from "../../utils/formatted-amount";
import { OrderTotal } from "../../components/order-total/order-total";

export const FeedPage: FC = () => {
  return (
    <>
      <div className={styles.container}>
        <p className="text text_type_main-large mt-10 mb-5">Лента заказов</p>
        <div className={styles.row}>
          <div className={styles.feed}>
            <OrderListItem
              date="2022-03-05T01:23:45"
              id="0123"
              ingredients={
                [
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                ] as any
              }
              price={456}
              title="some"
            />
            <OrderListItem
              date="2022-03-05T01:23:45"
              id="0123"
              ingredients={
                [
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                ] as any
              }
              price={456}
              title="some"
            />
            <OrderListItem
              date="2022-03-05T01:23:45"
              id="0123"
              ingredients={
                [
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                ] as any
              }
              price={456}
              title="some"
            />
            <OrderListItem
              date="2022-03-05T01:23:45"
              id="0123"
              ingredients={
                [
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                ] as any
              }
              price={456}
              title="some"
            />
            <OrderListItem
              date="2022-03-05T01:23:45"
              id="0123"
              ingredients={
                [
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                ] as any
              }
              price={456}
              title="some"
            />
            <OrderListItem
              date="2022-03-05T01:23:45"
              id="0123"
              ingredients={
                [
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                ] as any
              }
              price={456}
              title="some"
            />
          </div>
          <div className={styles.summary}>
            <div className={styles.orderNumbers}>
              <OrderNumbers
                orderIds={["034533", "034533", "034533", "034533", "034533"]}
                title="Готовы:"
                mode={OrderNumbersMode.Completed}
              ></OrderNumbers>
              <OrderNumbers
                orderIds={["034538"]}
                title="В работе:"
              ></OrderNumbers>
            </div>
            <OrderTotal title="Выполнено за все время:" total={28752} />
            <OrderTotal title="Выполнено за сегодня:" total={138} />
          </div>
        </div>
      </div>
    </>
  );
};
