import { FC } from "react";
import styles from "./feed.module.css";
import { OrderListItem } from "../../components/order-list-item/order-list-item";

export const FeedPage: FC = () => {
  return (
    <>
      <div className={styles.container}>
        <p className="text text_type_main-large mt-10 mb-5">Лента заказов</p>
        <div className={styles.row}>
          <div className={styles.column}>
            <OrderListItem
              date="2022-03-05T01:23:45"
              id="0123"
              ingredients={
                [
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                ] as any
              }
              price={456}
              title="some"
            />
            <OrderListItem
              date="2022-03-05T01:23:45"
              id="0123"
              ingredients={
                [
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                ] as any
              }
              price={456}
              title="some"
            />
            <OrderListItem
              date="2022-03-05T01:23:45"
              id="0123"
              ingredients={
                [
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                ] as any
              }
              price={456}
              title="some"
            />
            <OrderListItem
              date="2022-03-05T01:23:45"
              id="0123"
              ingredients={
                [
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                ] as any
              }
              price={456}
              title="some"
            />
            <OrderListItem
              date="2022-03-05T01:23:45"
              id="0123"
              ingredients={
                [
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                ] as any
              }
              price={456}
              title="some"
            />
            <OrderListItem
              date="2022-03-05T01:23:45"
              id="0123"
              ingredients={
                [
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                  {
                    image_mobile:
                      "https://code.s3.yandex.net/react/code/cheese-mobile.png",
                  },
                ] as any
              }
              price={456}
              title="some"
            />
          </div>
          <div className={styles.column}>2</div>
        </div>
      </div>
    </>
  );
};
